---
- name: Add CMDB CI to AAP Inventory if CI does not exist
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get the Inventory name from Running Job
      ansible.controller.job_list:
        status: running
        query: {"name": "EDA SNOW Update Inventory"}
      register: job_list

    - name: 'Ensure CI {{ ansible_eda.event.payload.ci_name }} exists in the Hosts from ServiceNow Inventory'
      ansible.controller.host:
        name: '{{ ansible_eda.event.payload.ci_name }}'
        inventory: "{{ job_list.results[0].summary_fields.inventory.name }}"
        state: present
        enabled: true