---
- name: Close ServiceNow Incident
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Close ServiceNow Incident
      servicenow.itsm.incident:
        state: resolved
        number: "{{ ansible_eda.event.payload.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "{{ message_for_snow.stdout_lines | join('\n') }}"
        caller: admin
        other:
          work_notes: "{{ message_for_snow.stdout_lines | join('\n') }}"
      register: update_incident
      retries: 5
      delay: 10
      until: update_incident is not failed