---
- name: listen for incidents from ServiceNows
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from servicenow business rules
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: '{{ TOKEN }}'
      filters:
       - ansible.eda.normalize_keys:

  ## Hello world

  rules:
    - name: Hello world
      condition: event.payload.number is defined and event.payload.description is search("Print Hello world", ignorecase=true)
      action:
        run_job_template:
          name: 'Hello world'
          organization: Default
          variables:
            webhook_payload: "{{ event.payload }}"

    # - name: Linux EDA disk pressure
    #   condition: event.payload.number is defined and event.payload.description is search("Linux Filesystem", ignorecase=true)
    #   action:
    #     run_job_template:
    #       name: Linux EDA Filesystem
    #       organization: Default
