---
- name: listen for Dynatrace events
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from dynatrace
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:

  ## OS Service Monitoring

  rules:
    - name: Linux EDA Service restarts
      condition: incident is defined and short_description is search("Linux Service is not running")
      action:
        run_job_template:
          name: Linux EDA Restart Service
          organization: Default
