---
- name: listen for incidents from ServiceNows
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from servicenow business rules
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: '{{ token }}'
        certfile: '/runner/server.cert'
        keyfile: '/runner/server.key'
      filters:
       - ansible.eda.normalize_keys:

  ## Hello world

  rules:
    - name: Open firewall port 8080
      condition: event.payload.ci_name is defined and event.payload.number is defined and event.payload.description is search("firewall", ignorecase=true) and event.payload.description is search("port", ignorecase=true) and event.payload.description is search("open", ignorecase=true)
      action:
        run_workflow_template:
          name: 'Hello world'
          organization: Default
