---
- name: Move CR Task to In Progress state and Fix
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Change state of the change task
      servicenow.itsm.change_request_task_info:
        query:
          - change_request: = {{ ansible_eda.event.payload.cr_id }}
      delegate_to: localhost
      register: task_number

    # - name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
    #   ansible.builtin.yum:
    #     name:
    #       - firewalld
    #     state: present
        
    # - name: Check if firewalld is running
    #   ansible.builtin.service:
    #     name: firewalld
    #     state: started

    # - name: Get port number
    #   ansible.builtin.set_fact:
    #     port_number: "{{ ansible_eda.event.payload.description | regex_search('[0-9]+') }}"
    
    # - name: 'Open port {{ port_number }} with firewalld (permanent)'
    #   firewalld:
    #     port: '{{ port_number }}/tcp'
    #     permanent: true
    #     state: enabled

    # - name: Check if firewalld is running
    #   ansible.builtin.service:
    #     name: firewalld
    #     state: reloaded

    # - name: get service status
    #   ansible.builtin.command:
    #     cmd: firewall-cmd --list-all
    #   register: service_status

    - name: "Export variable"
      set_stats:
        data:
          message_for_snow: 'All tasks are Closed'

    - name: "Export variable"
      set_stats:
        data:
          message_for_snow: "{{ item.number }}"
      loop: "{{ task_number.records }}"

    - name: Close a change task
      servicenow.itsm.change_request_task:
        state: closed
        close_code: "successful"
        close_notes: "Closed"
        number: "CTASK0010007"
#      loop: "{{ task_number.records }}"

  
