---
- name: Move Incident to In Progress state and Fix
  hosts: '{{ ansible_eda.event.payload.ci_name }}'
  gather_facts: no
  tasks:
    - name: Move Incident to In Progress state
      servicenow.itsm.incident:
        number: '{{ ansible_eda.event.payload.number }}'
        state: in_progress
        other:
          work_notes: "Event Driven Ansible is investigating"
      delegate_to: localhost
      register: update_incident
      retries: 5
      delay: 10
      until: update_incident is not failed

    - name: Check if firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Get port number
      ansible.builtin.set_fact:
        port_number: "{{ ansible_eda.event.payload.description | regex_search('[0-9]+') }}"

    - name: 'Open port {{ port_number }} with firewalld (permanent)'
      firewalld:
        port: '{{ port_number }}/tcp'
        permanent: true
        state: enabled

    - name: Check if firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: get service status
      ansible.builtin.command:
        cmd: firewall-cmd --list-all
      register: service_status

    - name: "Export variable"
      set_stats:
        data:
          message_for_snow:  '{{ service_status }}'

  
