---
- name: Validating received Incident information with actual Incident info from SNOW
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.itsm

  tasks:
    - name: 'Retrieve incident {{ ansible_eda.event.payload.number }} info'
      servicenow.itsm.incident_info:
        number: '{{ ansible_eda.event.payload.number }}'
      register: inc_info

    - debug:
        msg: '{{ inc_info }}'

    - name: Check if payload and Incident information match and Incident is in New state (Ignore all other)
      fail:
        msg: >
          Supplied information and Incident information do not match! Workflow will not progress.
      when: ansible_eda.event.payload.ci_name != inc_info.[].cmdb_ci or ansible_eda.event.payload.description != inc_info.[].short_description

    - name: Both Incidents match. Continue with remediation
      debug:
        msg: >
          'Success! Both Incidents {{ ansible_eda.event.payload.number }} match. Continue with remediation'
      when: ansible_eda.event.payload.ci_name == inc_info.[].cmdb_ci and ansible_eda.event.payload.description == inc_info.[].short_description