---
- name: hello world
  hosts: localhost
  tasks:
    - name: Print the webhook payload
      debug:
        var: {{ ansible_eda }}
        
    - name: Hello world
      debug:
        msg: "{{ ansible_eda }}"
