---

- name: hello world
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Hello world
    debug:
      msg: "Hello world {{ event_payload.number }}, {{ event_payload.ci_name }}, {{ event_payload.description }}"
