---

- name: hello world
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Hello world
    debug:
      msg: "Hello world {{ ansible_eda.event.payload.number }}, {{ ansible_eda.event.payload.ci_name }}, {{ ansible_eda.event.payload.description }}"
