---
- name: hello world
  hosts: localhost
  tasks:
    - name: Hello world
      debug:
        msg: "{{ ansible_eda.payload.number }}, {{ ansible_eda.payload.cmdb_ci }}, {{ ansible_eda.payload.description }}"
